// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/lib-commons/v5/commons/log (interfaces: Logger)
//
// Generated by this command:
//
//	mockgen --destination=log_mock.go --package=log . Logger
//

package log

import libobslog "github.com/LerianStudio/lib-observability/log"

// MockLogger is a mock of Logger interface.
type MockLogger = libobslog.MockLogger

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder = libobslog.MockLoggerMockRecorder

// NewMockLogger creates a new mock instance.
var NewMockLogger = libobslog.NewMockLogger
