// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/lib-commons/commons (interfaces: App)
//
// Generated by this command:
//
//	mockgen --destination=app_mock.go --package=commons . App
//

// Package commons is a generated GoMock package.
package commons

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockApp) Run(launcher *Launcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", launcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAppMockRecorder) Run(launcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockApp)(nil).Run), launcher)
}
